name: "jellycli"
description: "Add-on providing audio client using jellycli"
version: "1.0.0"
slug: "jellycli"

arch:
  - aarch64
  - amd64
audio: true
startup: application
host_network: true
map:
  - config:rw
devices:
  - /dev/snd
