name: "mopidy-speaker"
description: "Mopidy installation tuned to be a speaker for Jellyfin"
version: "1.0.1"
slug: "mopidy-speaker"

arch:
  - aarch64
  - amd64
audio: true
startup: application
host_network: true
map:
  - config:rw
devices:
  - /dev/snd
ports:
  6600/tcp: 6600
  6680/tcp: 6680
